language: node_js
node_js:
- node
- '7'
- '6'
- '6.0'
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: barsju@gmail.com
  api_key:
    secure: ejrouZZV4XVcmVhLl2LFeeHiuc4B9pVx8zpXT7HLjmNGBj2C2kz9I/5WXJthodFLHi4Jx4HHqJxwI1uCGRGNomAQ6PlmIacZFSVsIio5hIvHfSaPwbqyl9MXpmVXaEZvael8YFJQ3QFnxnASULC78RIgBlvdj/2G/R8YYR+/S3OajUb19C7vXmJkuJ9sqATs+jKhT3Q6gfSBYDwFHO6RJVUVVqBgjRUun8xSEEpvviFvfla9QAoa6E02lHaqM8bZiWxzp8ufCAiFq9PZjxnhjxsCbExM9I00ve2Arm9aLKn3mWblL/WnV0QFUxXgi32qZSDVcDvrnjugN0WiB6Lss+pANU7p9RUjLeYdTe2PgvjOw2sfnCL//GednJ0OEPE534F0GjCEPFwgo748+UjDdr+OfDXoTvA+dSH4OY8N9C1pvRWtmGABgnCrCZyFIiKZC/oUCZRSW2gjOHXUSfq+SKrJ56CqyAU9Cweya36HyraqAafHp1hzKUetTUCEyVsFn+3F64Bz1X64XGd2fblXhT2c1eaAqheK7+3t9mK8I3+Yqlsj6VSVf/mCv4dmrzZuT3UZrblXfX3ZQ6Z3h9W1A8wJ8D4KKkdApAsE+ge2IC6/Bmt9aOog9n2EXxUEXm4cCTUITi22oD7uifBrzifCww0QPWDqCuOFDdCNS+alUlw=
  on:
    tags: true
    repo: sjurba/rebase-editor
